### ISSUE TITLE
[SUGGESTION] Move $template argument from init command to options

### ISSUE THREAD

**Issue by audungk** [vgno/getroc#29]
Currently, a new roc-project is initialized with `roc init [template] [version]`, after you have created a working directory. At it's current state, the documentation available at getroc.org and from the cli is not very clear on what you are initializing (A Roc-app? A Roc-React app? A React and reflux app?), and the template argument to `roc init` is not immediately obvious.

I therefore suggest to change the `roc init`arguments to `roc init [name]`, and have the roc cli create the project folder and open for either setting the template as an option with -T or --template, or asking for it in the setup process. This would help in strengthening _roc_ as framework, making it more obvious that you are building a _roc-app_, using _roc-templates_ thus setting react and reflux as technology roc build upon instead of technology roc uses.

**Comment by dlmr** [comment]
I believe this is addressed with the new alias for `init` named `new` that requires a name that will be used to create a new folder. `[template]` and `[version]` are optional here and if no template is provided the user will be presented with a list of default ones.

```
roc new <name>  [template] [version]
```

See here https://github.com/rocjs/roc/blob/master/docs/DefaultCommands.md#new

Please open this issue if you think that we still can address this in a better way! The PR that you created is still open and will be used in the future #30 .
